from __future__ import annotations

from flask import Response


def get_four_chart_dashboard_html_v1() -> Response:
    html = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Jack AI Capital OS</title>
<script src="https://unpkg.com/lightweight-charts@4.2.0/dist/lightweight-charts.standalone.production.js"></script>
<style>
:root{--bg:#0b0f14;--bar:#0f1722;--panel:#111827;--line:#263241;--text:#dbe7f3;--muted:#8b98a8;--g:#22c55e;--r:#ef4444;--y:#eab308;--b:#3b82f6}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Arial,Helvetica,sans-serif;overflow:hidden}.app{height:100vh;display:grid;grid-template-rows:48px 1fr 230px}.bar{display:flex;gap:8px;align-items:center;padding:7px 10px;background:var(--bar);border-bottom:1px solid var(--line)}.brand{font-weight:900;font-size:13px}.sym{width:92px;background:#070b11;border:1px solid var(--line);color:var(--text);border-radius:6px;padding:7px;font-weight:800}.btn,.tf,.pill{border:1px solid var(--line);background:#121b28;color:var(--text);border-radius:6px;padding:7px 10px;font-size:12px;cursor:pointer;text-decoration:none}.tf.active{background:#1d4ed8;border-color:#60a5fa}.pill{cursor:default;color:var(--muted)}.cmd{margin-left:auto;font-weight:900}.red{color:var(--r)}.green{color:var(--g)}.yellow{color:var(--y)}.muted{color:var(--muted)}
.main{display:grid;grid-template-rows:1fr 58px}.chartBox{margin:10px;border:1px solid var(--line);background:#080c12;position:relative}.chartInfo{position:absolute;left:12px;top:10px;display:flex;gap:8px;z-index:2}.badge{background:rgba(15,23,34,.9);border:1px solid var(--line);padding:5px 8px;border-radius:6px;font-size:12px;color:var(--muted)}#chart{width:100%;height:100%}.strip{display:grid;grid-template-columns:repeat(4,1fr) 2fr;gap:8px;padding:8px 10px;background:var(--bar);border-top:1px solid var(--line)}.box{border:1px solid var(--line);background:#101824;border-radius:8px;padding:7px 9px}.k{font-size:10px;color:var(--muted);text-transform:uppercase}.v{font-size:14px;font-weight:900;margin-top:3px}.read{font-size:12px;color:var(--muted);line-height:1.4}
.term{display:grid;grid-template-rows:38px 1fr;background:#101824;border-top:1px solid var(--line)}.tabs{display:flex;background:#0a0f16;border-bottom:1px solid var(--line);padding-left:8px}.tab{padding:10px 14px;color:var(--muted);font-size:12px;cursor:pointer}.tab.active{background:#101824;color:var(--text);border:1px solid var(--line);border-bottom:0;border-radius:8px 8px 0 0}.body{overflow:auto;padding:10px}.tbl{width:100%;border-collapse:collapse;font-size:12px}.tbl th,.tbl td{padding:8px 10px;border-bottom:1px solid #223044;text-align:left}.tbl th{color:var(--muted);background:#0d1520}.list{margin:0;padding:0;list-style:none}.list li{padding:8px 10px;border-bottom:1px solid #223044;color:#cbd5e1;font-size:12px}
@media(max-width:900px){body{overflow:auto}.app{height:auto;min-height:100vh;grid-template-rows:auto 620px 300px}.bar{flex-wrap:wrap}.strip{grid-template-columns:repeat(2,1fr)}}
</style>
</head>
<body>
<div class="app">
 <div class="bar"><div class="brand">JACK AI CAPITAL OS</div><input id="symbol" class="sym" value="GBPJPY"><button class="tf active" data-tf="H1" onclick="setTF('H1')">H1</button><button class="tf" data-tf="D1" onclick="setTF('D1')">D1</button><button class="tf" data-tf="M15" onclick="setTF('M15')">M15</button><button class="tf" data-tf="M5" onclick="setTF('M5')">M5</button><button class="btn" onclick="loadAll(true)">Refresh</button><button class="btn" onclick="saveNow(true)">Save Now</button><a id="dailyLink" class="btn" target="_blank">Daily Summary</a><span class="pill">AUTO SAVE ON · 30s</span><span id="save" class="pill">Loading</span><span id="cmd" class="cmd muted">LOADING</span><span id="score" class="pill">—</span></div>
 <div class="main"><div class="chartBox"><div class="chartInfo"><span class="badge" id="chartSym">GBPJPY</span><span class="badge" id="chartTf">H1</span><span class="badge" id="chartState">Loading</span><span class="badge">EMA50 · BB Mid · YH/YL</span><span class="badge" id="time">—</span></div><div id="chart"></div></div><div class="strip"><div class="box"><div class="k">D1</div><div class="v" id="d1">—</div></div><div class="box"><div class="k">H1</div><div class="v" id="h1">—</div></div><div class="box"><div class="k">M15</div><div class="v" id="m15">—</div></div><div class="box"><div class="k">M5</div><div class="v" id="m5">—</div></div><div class="box"><div class="k">AI Read</div><div class="read" id="read">Reading...</div></div></div></div>
 <div class="term"><div class="tabs"><div class="tab active" onclick="show('overview',this)">Overview</div><div class="tab" onclick="show('blockers',this)">Blockers</div><div class="tab" onclick="show('reasons',this)">Reasons</div><div class="tab" onclick="show('memory',this)">Memory</div><div class="tab" onclick="show('daily',this)">Daily</div></div><div class="body" id="body">Loading</div></div>
</div>
<script>
let R=null,C=null,M=null,D=null,TF='H1',TAB='overview',LAST=localStorage.getItem('jack_last_saved_key')||'';
let chart=null,candleSeries=null,emaSeries=null,bbMidSeries=null,levelLines=[];
function f(v){return(v===null||v===undefined||v==='')?'—':v}function c(x){x=String(x||'').toLowerCase();if(x.includes('long')||x.includes('ready'))return'green';if(x.includes('watch')||x.includes('prepare'))return'yellow';if(x.includes('wait')||x.includes('unclear')||x.includes('no'))return'red';return'muted'}
function st(tf){let s=((R||{}).four_timeframe_signals||{}).signals||{},o=s[tf]||{};return tf==='D1'?o.signal:tf==='H1'?o.regime:o.signal}
function initChart(){let el=document.getElementById('chart');if(chart){chart.remove()}chart=LightweightCharts.createChart(el,{layout:{background:{color:'#080c12'},textColor:'#cbd5e1'},grid:{vertLines:{color:'#111827'},horzLines:{color:'#1b2533'}},rightPriceScale:{borderColor:'#263241'},timeScale:{borderColor:'#263241',timeVisible:true,secondsVisible:false},crosshair:{mode:LightweightCharts.CrosshairMode.Normal}});candleSeries=chart.addCandlestickSeries({upColor:'#22c55e',downColor:'#ef4444',borderUpColor:'#22c55e',borderDownColor:'#ef4444',wickUpColor:'#22c55e',wickDownColor:'#ef4444'});emaSeries=chart.addLineSeries({color:'#3b82f6',lineWidth:2,title:'EMA50'});bbMidSeries=chart.addLineSeries({color:'#a78bfa',lineWidth:1,title:'BB Mid'});new ResizeObserver(()=>chart.applyOptions({width:el.clientWidth,height:el.clientHeight})).observe(el);chart.applyOptions({width:el.clientWidth,height:el.clientHeight})}
function tvTime(t){let d=new Date(t);if(isNaN(d.getTime()))return Math.floor(Date.now()/1000);return Math.floor(d.getTime()/1000)}
function sma(data,n){let out=[];for(let i=0;i<data.length;i++){if(i<n-1)continue;let s=0;for(let j=i-n+1;j<=i;j++)s+=data[j].close;out.push({time:data[i].time,value:+(s/n).toFixed(5)})}return out}
function setTF(tf){TF=tf;document.querySelectorAll('.tf').forEach(b=>b.classList.toggle('active',b.dataset.tf===tf));draw()}
function draw(){if(!C||!R)return;if(!chart)initChart();document.getElementById('chartTf').textContent=TF;document.getElementById('chartState').textContent=f(st(TF));document.getElementById('chartState').className='badge '+c(st(TF));levelLines.forEach(x=>candleSeries.removePriceLine(x));levelLines=[];let rows=(((C.timeframes||{})[TF]||{}).candles||[]).slice(-220);let data=rows.map(x=>({time:tvTime(x.timestamp||x.time),open:+x.open,high:+x.high,low:+x.low,close:+x.close})).filter(x=>x.open&&x.high&&x.low&&x.close);candleSeries.setData(data);emaSeries.setData(sma(data,50));bbMidSeries.setData(sma(data,20));let s=((R.four_timeframe_signals||{}).signals||{})[TF]||{},ec=R.entry_context||{};let levels=[['YH',s.yesterday_high||ec.yesterday_high,'#eab308'],['YL',s.yesterday_low||ec.yesterday_low,'#eab308'],['Ref',s.entry_price||ec.entry_price,'#f97316']];levels.forEach(z=>{if(z[1]==null)return;levelLines.push(candleSeries.createPriceLine({price:+z[1],color:z[2],lineWidth:1,lineStyle:LightweightCharts.LineStyle.Dashed,axisLabelVisible:true,title:z[0]}))});chart.timeScale().fitContent()}
function key(){let s=((R||{}).four_timeframe_signals||{}).signals||{},t=x=>((s[x]||{}).latest_timestamp||'');return[(R.symbol||'GBPJPY'),R.final_command,R.readiness_stage,R.readiness_score,t('D1'),t('H1'),t('M15'),t('M5')].join('|')}
async function loadAll(force=false){let sym=document.getElementById('symbol').value||'GBPJPY';document.getElementById('chartSym').textContent=sym;document.getElementById('dailyLink').href='/api/jack-brain/daily-ai-summary-v1?symbol='+encodeURIComponent(sym);let q='symbol='+encodeURIComponent(sym)+'&start_equity=500&target_equity=100000&current_equity=500&peak_equity=500&elapsed_days=0&total_days=365&consecutive_losses=0&news_risk=low';let rr=await Promise.all([fetch('/api/jack-brain/trade-readiness-v2?'+q),fetch('/api/jack-brain/latest-candles-v1?symbol='+encodeURIComponent(sym)+'&timeframes=D1,H1,M15,M5&limit=260'),fetch('/api/jack-brain/list-memory-v1?symbol='+encodeURIComponent(sym)+'&memory_type=dashboard_auto_snapshot&limit=5'),fetch('/api/jack-brain/daily-ai-summary-v1?symbol='+encodeURIComponent(sym))]);R=await rr[0].json();C=await rr[1].json();M=await rr[2].json();D=await rr[3].json();document.getElementById('cmd').textContent=R.final_command||'UNKNOWN';document.getElementById('cmd').className='cmd '+c(R.final_command);document.getElementById('score').textContent='Score '+f(R.readiness_score);['D1','H1','M15','M5'].forEach(x=>{let id=x.toLowerCase();document.getElementById(id).textContent=f(st(x));document.getElementById(id).className='v '+c(st(x))});document.getElementById('read').textContent=R.reason||'—';document.getElementById('time').textContent='Updated '+new Date().toLocaleTimeString();draw();render();await autoSave(force)}
async function saveNow(force=false){if(!R)return;let k=key();if(!force&&k===LAST){document.getElementById('save').textContent='No change';return}let tf=R.four_timeframe_summary||{},body={memory_type:'dashboard_auto_snapshot',symbol:R.symbol||'GBPJPY',title:'Auto Snapshot '+(R.final_command||''),content:`${R.symbol||'GBPJPY'} snapshot: command=${R.final_command}, stage=${R.readiness_stage}, score=${R.readiness_score}. D1=${tf.D1}, H1=${tf.H1}, M15=${tf.M15}, M5=${tf.M5}. ${R.reason||''}`,tags:['dashboard_auto_snapshot',R.final_command||'',R.readiness_stage||''],source:'four_chart_dashboard_v1',metadata:{snapshot_key:k,summary:R.four_timeframe_summary,score:R.readiness_score,blockers:R.blockers,reasons:R.reasons}};document.getElementById('save').textContent='Saving';let res=await fetch('/api/jack-brain/save-memory-v1',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let data=await res.json();if(data.ok){LAST=k;localStorage.setItem('jack_last_saved_key',k);document.getElementById('save').textContent='Saved '+new Date().toLocaleTimeString()}else document.getElementById('save').textContent='Save failed'}
async function autoSave(force=false){try{await saveNow(force)}catch(e){document.getElementById('save').textContent='Save error'}}
function show(t,el){TAB=t;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));el.classList.add('active');render()}function rows(a){return '<table class="tbl"><tbody>'+a.map(x=>`<tr><th>${x[0]}</th><td>${f(x[1])}</td></tr>`).join('')+'</tbody></table>'}function ul(a){return '<ul class="list">'+(a&&a.length?a:['None']).map(x=>`<li>${x}</li>`).join('')+'</ul>'}
function render(){let b=document.getElementById('body');if(!R){b.textContent='Loading';return}if(TAB==='overview')b.innerHTML=rows([['Command',R.final_command],['Stage',R.readiness_stage],['Score',R.readiness_score],['Selected Mode',R.selected_mode],['Next',R.next_action],['D1',st('D1')],['H1',st('H1')],['M15',st('M15')],['M5',st('M5')]]);if(TAB==='blockers')b.innerHTML=ul(R.blockers);if(TAB==='reasons')b.innerHTML=ul(R.reasons);if(TAB==='memory'){let it=(M||{}).items||[];b.innerHTML='<table class="tbl"><thead><tr><th>Time</th><th>Title</th><th>Text</th></tr></thead><tbody>'+it.map(x=>`<tr><td>${x.created_at||''}</td><td>${x.title||''}</td><td>${x.content||''}</td></tr>`).join('')+'</tbody></table>'}if(TAB==='daily')b.innerHTML=rows([['Count',(D||{}).snapshot_count],['Summary',(D||{}).human_summary],['Next Focus',((D||{}).next_focus||[]).join(' | ')]])}
loadAll(true).catch(e=>{document.getElementById('cmd').textContent='ERROR';document.getElementById('read').textContent=String(e)});setInterval(()=>loadAll(false),30000);
</script>
</body>
</html>'''
    return Response(html, mimetype="text/html")
