from __future__ import annotations

from flask import Response


def get_four_chart_dashboard_html_v1() -> Response:
    html = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Jack AI Capital OS</title>
<script src="https://unpkg.com/lightweight-charts@4.2.0/dist/lightweight-charts.standalone.production.js"></script>
<style>
:root{--bg:#0b0f14;--bar:#0f1722;--panel:#101824;--chart:#080c12;--line:#263241;--text:#dbe7f3;--muted:#8b98a8;--g:#22c55e;--r:#ef4444;--y:#eab308;--b:#3b82f6;--p:#a78bfa}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Arial,Helvetica,sans-serif;overflow:hidden}.app{height:100vh;display:grid;grid-template-rows:76px 1fr 214px}.bar{display:flex;gap:7px;align-items:center;padding:6px 8px;background:var(--bar);border-bottom:1px solid var(--line);flex-wrap:wrap}.brand{font-weight:900;font-size:13px}.sym{width:92px;background:#070b11;border:1px solid var(--line);color:var(--text);border-radius:6px;padding:6px 8px;font-weight:800}.btn,.pill,.tog{border:1px solid var(--line);background:#121b28;color:var(--text);border-radius:6px;padding:6px 9px;font-size:12px;cursor:pointer;text-decoration:none}.pill{cursor:default;color:var(--muted)}.tog.on{background:#1d4ed8;border-color:#60a5fa}.tog.off{opacity:.48}.cmd{margin-left:auto;font-weight:900}.green{color:var(--g)}.red{color:var(--r)}.yellow{color:var(--y)}.muted{color:var(--muted)}
.grid{display:grid;grid-template-columns:1fr 1fr;grid-template-rows:1fr 1fr;gap:8px;padding:8px;background:#070b10;min-height:0}.card{position:relative;border:1px solid var(--line);background:var(--chart);border-radius:8px;overflow:hidden;min-height:0}.head{position:absolute;left:8px;right:8px;top:7px;display:flex;gap:6px;align-items:center;z-index:2;pointer-events:none}.tfTitle{font-weight:900;background:rgba(15,23,34,.92);border:1px solid var(--line);border-radius:6px;padding:4px 7px;font-size:12px}.tag{background:rgba(15,23,34,.92);border:1px solid var(--line);border-radius:999px;padding:4px 7px;font-size:11px;color:var(--muted)}.chart{width:100%;height:100%}.mini{margin-left:auto;color:var(--muted);font-size:11px;background:rgba(15,23,34,.92);border:1px solid var(--line);border-radius:6px;padding:4px 7px}.tvlogo{position:absolute;left:8px;bottom:6px;font-weight:900;font-size:11px;color:#dbe7f3;opacity:.7;z-index:2}
.term{display:grid;grid-template-rows:38px 1fr;background:var(--panel);border-top:1px solid var(--line)}.strip{display:grid;grid-template-columns:repeat(4,1fr) 2fr;gap:8px;padding:6px 8px;border-bottom:1px solid var(--line);background:#0c131d}.box{border:1px solid var(--line);background:#101824;border-radius:7px;padding:5px 8px}.k{font-size:10px;color:var(--muted);text-transform:uppercase}.v{font-size:14px;font-weight:900;margin-top:2px}.read{font-size:12px;color:var(--muted);line-height:1.35}.tabs{display:flex;background:#0a0f16;border-bottom:1px solid var(--line);padding-left:8px}.tab{padding:9px 13px;color:var(--muted);font-size:12px;cursor:pointer}.tab.active{background:#101824;color:var(--text);border:1px solid var(--line);border-bottom:0;border-radius:8px 8px 0 0}.body{overflow:auto;padding:8px}.tbl{width:100%;border-collapse:collapse;font-size:12px}.tbl th,.tbl td{padding:7px 9px;border-bottom:1px solid #223044;text-align:left}.tbl th{width:220px;color:var(--muted);background:#0d1520}.list{margin:0;padding:0;list-style:none}.list li{padding:7px 9px;border-bottom:1px solid #223044;color:#cbd5e1;font-size:12px}
@media(max-width:900px){body{overflow:auto}.app{height:auto;min-height:100vh;grid-template-rows:auto 1200px 360px}.grid{grid-template-columns:1fr;grid-template-rows:repeat(4,300px)}.strip{grid-template-columns:repeat(2,1fr)}}
</style>
</head>
<body>
<div class="app">
 <div class="bar"><div class="brand">JACK AI CAPITAL OS</div><input id="symbol" class="sym" value="GBPJPY"><button class="btn" onclick="loadAll(true)">Refresh</button><button class="btn" onclick="saveNow(true)">Save Now</button><a id="dailyLink" class="btn" target="_blank">Daily Summary</a><span class="pill">4 CHARTS · BACKEND INDICATORS</span><button class="tog on" data-ind="ema50" onclick="toggleInd('ema50')">EMA50</button><button class="tog on" data-ind="ema20" onclick="toggleInd('ema20')">EMA20</button><button class="tog off" data-ind="sma14" onclick="toggleInd('sma14')">SMA14</button><button class="tog off" data-ind="sma20" onclick="toggleInd('sma20')">SMA20</button><button class="tog on" data-ind="bb" onclick="toggleInd('bb')">BB</button><span class="pill">LIVE REFRESH 5s</span><span class="pill">AUTO SAVE 30s</span><span id="save" class="pill">Loading</span><span id="cmd" class="cmd">LOADING</span><span id="score" class="pill">—</span></div>
 <div class="grid">
  <div class="card"><div class="head"><span class="tfTitle">D1</span><span id="tagD1" class="tag">—</span><span id="srcD1" class="tag">—</span><span id="miniD1" class="mini">—</span></div><div id="chartD1" class="chart"></div><div class="tvlogo">TV</div></div>
  <div class="card"><div class="head"><span class="tfTitle">H1</span><span id="tagH1" class="tag">—</span><span id="srcH1" class="tag">—</span><span id="miniH1" class="mini">—</span></div><div id="chartH1" class="chart"></div><div class="tvlogo">TV</div></div>
  <div class="card"><div class="head"><span class="tfTitle">M15</span><span id="tagM15" class="tag">—</span><span id="srcM15" class="tag">—</span><span id="miniM15" class="mini">—</span></div><div id="chartM15" class="chart"></div><div class="tvlogo">TV</div></div>
  <div class="card"><div class="head"><span class="tfTitle">M5</span><span id="tagM5" class="tag">—</span><span id="srcM5" class="tag">—</span><span id="miniM5" class="mini">—</span></div><div id="chartM5" class="chart"></div><div class="tvlogo">TV</div></div>
 </div>
 <div class="term"><div class="strip"><div class="box"><div class="k">D1</div><div class="v" id="d1">—</div></div><div class="box"><div class="k">H1</div><div class="v" id="h1">—</div></div><div class="box"><div class="k">M15</div><div class="v" id="m15">—</div></div><div class="box"><div class="k">M5</div><div class="v" id="m5">—</div></div><div class="box"><div class="k">AI Read</div><div class="read" id="read">Reading...</div></div></div><div class="tabs"><div class="tab active" onclick="show('overview',this)">Overview</div><div class="tab" onclick="show('live',this)">Live</div><div class="tab" onclick="show('indicators',this)">Indicators</div><div class="tab" onclick="show('markers',this)">Markers</div><div class="tab" onclick="show('blockers',this)">Blockers</div><div class="tab" onclick="show('reasons',this)">Reasons</div><div class="tab" onclick="show('memory',this)">Memory</div><div class="tab" onclick="show('daily',this)">Daily</div></div><div class="body" id="body">Loading</div></div>
</div>
<script>
let R=null,C=null,I=null,L=null,M=null,D=null,TAB='overview',LAST=localStorage.getItem('jack_last_saved_key')||'';const TFS=['D1','H1','M15','M5'];let charts={};let SHOW={ema50:true,ema20:true,sma14:false,sma20:false,bb:true};
function f(v){return(v===null||v===undefined||v==='')?'—':v}function css(x){x=String(x||'').toLowerCase();if(x.includes('long')||x.includes('ready'))return'green';if(x.includes('watch')||x.includes('prepare'))return'yellow';if(x.includes('wait')||x.includes('unclear')||x.includes('no'))return'red';return'muted'}
function color(x){let k=css(x);return k==='green'?'#22c55e':k==='yellow'?'#eab308':k==='red'?'#ef4444':'#8b98a8'}
function st(tf){let s=((R||{}).four_timeframe_signals||{}).signals||{},o=s[tf]||{};return tf==='D1'?o.signal:tf==='H1'?o.regime:o.signal}
function tvTime(t){let d=new Date(t);if(isNaN(d.getTime()))return Math.floor(Date.now()/1000);return Math.floor(d.getTime()/1000)}
function mapLine(series){return(series||[]).map(x=>({time:tvTime(x.timestamp),value:+x.value})).filter(x=>x.value)}
function live(tf){return(((L||{}).timeframes||{})[tf]||{})}
function toggleInd(name){SHOW[name]=!SHOW[name];document.querySelectorAll('[data-ind="'+name+'"]').forEach(b=>{b.classList.toggle('on',SHOW[name]);b.classList.toggle('off',!SHOW[name])});drawAll()}
function makeChart(tf){let el=document.getElementById('chart'+tf);if(charts[tf]){charts[tf].chart.remove()}let chart=LightweightCharts.createChart(el,{layout:{background:{color:'#080c12'},textColor:'#cbd5e1'},grid:{vertLines:{color:'#111827'},horzLines:{color:'#1b2533'}},rightPriceScale:{borderColor:'#263241'},timeScale:{borderColor:'#263241',timeVisible:true,secondsVisible:false},crosshair:{mode:LightweightCharts.CrosshairMode.Normal}});let candle=chart.addCandlestickSeries({upColor:'#22c55e',downColor:'#ef4444',borderUpColor:'#22c55e',borderDownColor:'#ef4444',wickUpColor:'#22c55e',wickDownColor:'#ef4444'});let series={ema50:chart.addLineSeries({color:'#3b82f6',lineWidth:2,title:'EMA50'}),ema20:chart.addLineSeries({color:'#38bdf8',lineWidth:1,title:'EMA20'}),sma14:chart.addLineSeries({color:'#eab308',lineWidth:1,title:'SMA14'}),sma20:chart.addLineSeries({color:'#f97316',lineWidth:1,title:'SMA20'}),bbUpper:chart.addLineSeries({color:'#a78bfa',lineWidth:1,title:'BB Upper'}),bbMiddle:chart.addLineSeries({color:'#a78bfa',lineWidth:1,title:'BB Mid'}),bbLower:chart.addLineSeries({color:'#a78bfa',lineWidth:1,title:'BB Lower'})};charts[tf]={chart,candle,series,lines:[]};new ResizeObserver(()=>chart.applyOptions({width:el.clientWidth,height:el.clientHeight})).observe(el);chart.applyOptions({width:el.clientWidth,height:el.clientHeight})}
function drawOne(tf){if(!charts[tf])makeChart(tf);let pack=charts[tf];pack.lines.forEach(x=>pack.candle.removePriceLine(x));pack.lines=[];let rows=(((C||{}).timeframes||{})[tf]||{}).candles||[];let limit=tf==='D1'?180:tf==='H1'?220:180;let data=rows.slice(-limit).map(x=>({time:tvTime(x.timestamp||x.time),open:+x.open,high:+x.high,low:+x.low,close:+x.close})).filter(x=>x.open&&x.high&&x.low&&x.close);pack.candle.setData(data);let ind=(((I||{}).timeframes||{})[tf]||{}).indicators||{};pack.series.ema50.setData(SHOW.ema50?mapLine(ind.ema50):[]);pack.series.ema20.setData(SHOW.ema20?mapLine(ind.ema20):[]);pack.series.sma14.setData(SHOW.sma14?mapLine(ind.sma14):[]);pack.series.sma20.setData(SHOW.sma20?mapLine(ind.sma20):[]);pack.series.bbUpper.setData(SHOW.bb?mapLine(ind.bb_upper):[]);pack.series.bbMiddle.setData(SHOW.bb?mapLine(ind.bb_middle):[]);pack.series.bbLower.setData(SHOW.bb?mapLine(ind.bb_lower):[]);let sig=(((R||{}).four_timeframe_signals||{}).signals||{})[tf]||{},ec=(R||{}).entry_context||{},lp=live(tf);let last=data[data.length-1];let s=f(st(tf));let livePrice=Number(lp.price||0)||((last||{}).close);let levels=[['YH',sig.yesterday_high||ec.yesterday_high,'#eab308'],['YL',sig.yesterday_low||ec.yesterday_low,'#eab308'],['Ref',sig.reference_price||ec.reference_price,'#f97316']];if(livePrice)levels.push(['Live',livePrice,color(s)]);levels.forEach(z=>{if(z[1]==null)return;pack.lines.push(pack.candle.createPriceLine({price:+z[1],color:z[2],lineWidth:z[0]==='Live'?2:1,lineStyle:z[0]==='Live'?LightweightCharts.LineStyle.Solid:LightweightCharts.LineStyle.Dashed,axisLabelVisible:true,title:z[0]}))});if(last){pack.candle.setMarkers([{time:last.time,position:'aboveBar',color:color(s),shape:'circle',text:s}])}else{pack.candle.setMarkers([])}pack.chart.timeScale().fitContent();let tag=document.getElementById('tag'+tf);tag.textContent=s;tag.className='tag '+css(s);let latest=(((I||{}).timeframes||{})[tf]||{}).latest_values||{};let rsi=((latest.rsi14||{}).value);document.getElementById('mini'+tf).textContent=livePrice?('Live '+Number(livePrice).toFixed(3)+' · RSI '+f(rsi)):'—';document.getElementById('src'+tf).textContent=(lp.source||'no_live_source').replaceAll('_',' ')}
function drawAll(){TFS.forEach(drawOne)}
function key(){let s=((R||{}).four_timeframe_signals||{}).signals||{},t=x=>((s[x]||{}).latest_timestamp||'');return[(R.symbol||'GBPJPY'),R.final_command,R.readiness_stage,R.readiness_score,t('D1'),t('H1'),t('M15'),t('M5')].join('|')}
async function refreshLiveOnly(){try{let sym=document.getElementById('symbol').value||'GBPJPY';let res=await fetch('/api/jack-brain/live-price-all-v1?symbol='+encodeURIComponent(sym)+'&timeframes=D1,H1,M15,M5');L=await res.json();drawAll();if(TAB==='live'||TAB==='markers')render()}catch(e){}}
async function loadAll(force=false){let sym=document.getElementById('symbol').value||'GBPJPY';document.getElementById('dailyLink').href='/api/jack-brain/daily-ai-summary-v1?symbol='+encodeURIComponent(sym);let q='symbol='+encodeURIComponent(sym)+'&start_equity=500&target_equity=100000&current_equity=500&peak_equity=500&elapsed_days=0&total_days=365&consecutive_losses=0&news_risk=low';let rr=await Promise.all([fetch('/api/jack-brain/trade-readiness-v2?'+q),fetch('/api/jack-brain/latest-candles-v1?symbol='+encodeURIComponent(sym)+'&timeframes=D1,H1,M15,M5&limit=260'),fetch('/api/jack-brain/indicator-overlay-all-v1?symbol='+encodeURIComponent(sym)+'&timeframes=D1,H1,M15,M5&limit=320'),fetch('/api/jack-brain/live-price-all-v1?symbol='+encodeURIComponent(sym)+'&timeframes=D1,H1,M15,M5'),fetch('/api/jack-brain/list-memory-v1?symbol='+encodeURIComponent(sym)+'&memory_type=dashboard_auto_snapshot&limit=5'),fetch('/api/jack-brain/daily-ai-summary-v1?symbol='+encodeURIComponent(sym))]);R=await rr[0].json();C=await rr[1].json();I=await rr[2].json();L=await rr[3].json();M=await rr[4].json();D=await rr[5].json();document.getElementById('cmd').textContent=R.final_command||'UNKNOWN';document.getElementById('cmd').className='cmd '+css(R.final_command);document.getElementById('score').textContent='Score '+f(R.readiness_score);TFS.forEach(x=>{let id=x.toLowerCase();document.getElementById(id).textContent=f(st(x));document.getElementById(id).className='v '+css(st(x))});document.getElementById('read').textContent=R.reason||'—';drawAll();render();await autoSave(force)}
async function saveNow(force=false){if(!R)return;let k=key();if(!force&&k===LAST){document.getElementById('save').textContent='No change';return}let tf=R.four_timeframe_summary||{},body={memory_type:'dashboard_auto_snapshot',symbol:R.symbol||'GBPJPY',title:'Auto Snapshot '+(R.final_command||''),content:`${R.symbol||'GBPJPY'} snapshot: command=${R.final_command}, stage=${R.readiness_stage}, score=${R.readiness_score}. D1=${tf.D1}, H1=${tf.H1}, M15=${tf.M15}, M5=${tf.M5}. ${R.reason||''}`,tags:['dashboard_auto_snapshot',R.final_command||'',R.readiness_stage||''],source:'four_chart_dashboard_v1',metadata:{snapshot_key:k,summary:R.four_timeframe_summary,score:R.readiness_score,blockers:R.blockers,reasons:R.reasons}};document.getElementById('save').textContent='Saving';let res=await fetch('/api/jack-brain/save-memory-v1',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let data=await res.json();if(data.ok){LAST=k;localStorage.setItem('jack_last_saved_key',k);document.getElementById('save').textContent='Saved '+new Date().toLocaleTimeString()}else document.getElementById('save').textContent='Save failed'}
async function autoSave(force=false){try{await saveNow(force)}catch(e){document.getElementById('save').textContent='Save error'}}
function show(t,el){TAB=t;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));el.classList.add('active');render()}function rows(a){return '<table class="tbl"><tbody>'+a.map(x=>`<tr><th>${x[0]}</th><td>${f(x[1])}</td></tr>`).join('')+'</tbody></table>'}function ul(a){return '<ul class="list">'+(a&&a.length?a:['None']).map(x=>`<li>${x}</li>`).join('')+'</ul>'}
function indicatorRows(){let out=[];TFS.forEach(tf=>{let v=(((I||{}).timeframes||{})[tf]||{}).latest_values||{};out.push([tf+' EMA20',((v.ema20||{}).value)]);out.push([tf+' EMA50',((v.ema50||{}).value)]);out.push([tf+' BB Mid',((v.bb_middle||{}).value)]);out.push([tf+' ATR14',((v.atr14||{}).value)]);out.push([tf+' RSI14',((v.rsi14||{}).value)])});return out}
function liveRows(){return TFS.map(tf=>{let x=live(tf);return[tf,(x.price||'—')+' · '+(x.source||'—')+' · '+(x.timestamp||'—')]})}
function markerRows(){return TFS.map(tf=>[tf,st(tf)+' · marker on latest candle · live reference line '+f(live(tf).price)])}
function render(){let b=document.getElementById('body');if(!R){b.textContent='Loading';return}if(TAB==='overview')b.innerHTML=rows([['Command',R.final_command],['Stage',R.readiness_stage],['Score',R.readiness_score],['Selected Mode',R.selected_mode],['Next',R.next_action],['D1',st('D1')],['H1',st('H1')],['M15',st('M15')],['M5',st('M5')]]);if(TAB==='live')b.innerHTML=rows(liveRows());if(TAB==='indicators')b.innerHTML=rows(indicatorRows());if(TAB==='markers')b.innerHTML=rows(markerRows());if(TAB==='blockers')b.innerHTML=ul(R.blockers);if(TAB==='reasons')b.innerHTML=ul(R.reasons);if(TAB==='memory'){let it=(M||{}).items||[];b.innerHTML='<table class="tbl"><thead><tr><th>Time</th><th>Title</th><th>Text</th></tr></thead><tbody>'+it.map(x=>`<tr><td>${x.created_at||''}</td><td>${x.title||''}</td><td>${x.content||''}</td></tr>`).join('')+'</tbody></table>'}if(TAB==='daily')b.innerHTML=rows([['Count',(D||{}).snapshot_count],['Summary',(D||{}).human_summary],['Next Focus',((D||{}).next_focus||[]).join(' | ')]])}
loadAll(true).catch(e=>{document.getElementById('cmd').textContent='ERROR';document.getElementById('read').textContent=String(e)});setInterval(()=>refreshLiveOnly(),5000);setInterval(()=>loadAll(false),30000);
</script>
</body>
</html>'''
    return Response(html, mimetype="text/html")
